name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python (adjust version if you want, e.g. "3.10")
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install system dependencies (Graphviz is needed by `diagrams`)
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      # 4. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run all Python scripts that generate diagrams
      - name: Generate diagrams
        run: |
          mkdir -p diagrams_output
          pwd && ls 
          for file in scripts/*.py; do
            echo "Running $file ..."
            python "$file"
          done
          # Move all PNG/SVG outputs into a dedicated folder
          mv *.png diagrams_output/ || true
          mv *.svg diagrams_output/ || true

      # 6. Upload generated diagrams as artifacts
      - name: Upload diagrams
        uses: actions/upload-artifact@v4
        with:
          name: diagrams
          path: diagrams_output/